<?php
namespace aae\ui\elements {
	require_once strstr(__FILE__, 'Test', true).'/aae/autoload/AutoLoader.php';
	class PaginationNavigationTest extends \PHPUnit_Framework_TestCase {
        use \aae\unitTesting\TestFilesTrait;

        public function provider_setPageMenu() {
            return array(
                array(100,1,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => ' hidden',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => '',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => '',
                        'pagination0' => 1,
                        'pagination1' => 2,
                        'pagination2' => 3,
                        'pagination3' => 4,
                        'pagination4' => 5,
                        'pagination10' => 11
                    ]
                ),
                array(100,2,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 1,
                        'pagination0' => 2,
                        'pagination1' => 3,
                        'pagination2' => 4,
                        'pagination3' => 5,
                        'pagination4' => '',
                        'pagination10' => 12
                    ]
                ),
                array(100,3,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => 1,
                        'pagination-1' => 2,
                        'pagination0' => 3,
                        'pagination1' => 4,
                        'pagination2' => 5,
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 13
                    ]
                ),
                array(100,4,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => 1,
                        'pagination-2' => 2,
                        'pagination-1' => 3,
                        'pagination0' => 4,
                        'pagination1' => 5,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 14
                    ]
                ),
                array(100,5,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => 1,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 4,
                        'pagination0' => 5,
                        'pagination1' => 6,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 15
                    ]
                ),
                array(100,6,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => 1,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 5,
                        'pagination0' => 6,
                        'pagination1' => 7,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 16
                    ]
                ),
                array(100,12,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => 2,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 11,
                        'pagination0' => 12,
                        'pagination1' => 13,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 22
                    ]
                ),
                array(100,100,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => '',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => ' hidden',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 90,
                        'pagination-4' => 96,
                        'pagination-3' => 97,
                        'pagination-2' => 98,
                        'pagination-1' => 99,
                        'pagination0' => 100,
                        'pagination1' => '',
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(100,99,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 89,
                        'pagination-4' => '',
                        'pagination-3' => 96,
                        'pagination-2' => 97,
                        'pagination-1' => 98,
                        'pagination0' => 99,
                        'pagination1' => 100,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(100,98,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 88,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => 96,
                        'pagination-1' => 97,
                        'pagination0' => 98,
                        'pagination1' => 99,
                        'pagination2' => 100,
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(100,97,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 87,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 96,
                        'pagination0' => 97,
                        'pagination1' => 98,
                        'pagination2' => 99,
                        'pagination3' => 100,
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(100,96,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => 86,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 95,
                        'pagination0' => 96,
                        'pagination1' => 97,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 100
                    ]
                ),
                array(100,89,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => 79,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 88,
                        'pagination0' => 89,
                        'pagination1' => 90,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 99
                    ]
                ),
                array(1,1,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => ' hidden',
                        'paginationHide0' => '',
                        'paginationHide1' => ' hidden',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => '',
                        'pagination0' => 1,
                        'pagination1' => '',
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(2,1,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => ' hidden',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => '',
                        'pagination0' => 1,
                        'pagination1' => 2,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(3,1,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => ' hidden',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => '',
                        'pagination0' => 1,
                        'pagination1' => 2,
                        'pagination2' => 3,
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(4,1,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => ' hidden',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => '',
                        'pagination0' => 1,
                        'pagination1' => 2,
                        'pagination2' => 3,
                        'pagination3' => 4,
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(5,1,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => ' hidden',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => '',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => '',
                        'pagination0' => 1,
                        'pagination1' => 2,
                        'pagination2' => 3,
                        'pagination3' => 4,
                        'pagination4' => 5,
                        'pagination10' => ''
                    ]
                ),
                array(6,1,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => ' hidden',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => '',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => '',
                        'pagination0' => 1,
                        'pagination1' => 2,
                        'pagination2' => 3,
                        'pagination3' => 4,
                        'pagination4' => 5,
                        'pagination10' => 6
                    ]
                ),
                array(7,1,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => ' hidden',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => '',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => '',
                        'pagination0' => 1,
                        'pagination1' => 2,
                        'pagination2' => 3,
                        'pagination3' => 4,
                        'pagination4' => 5,
                        'pagination10' => 7
                    ]
                ),
                array(2,2,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => ' hidden',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 1,
                        'pagination0' => 2,
                        'pagination1' => '',
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(3,2,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 1,
                        'pagination0' => 2,
                        'pagination1' => 3,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(4,2,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 1,
                        'pagination0' => 2,
                        'pagination1' => 3,
                        'pagination2' => 4,
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(5,2,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 1,
                        'pagination0' => 2,
                        'pagination1' => 3,
                        'pagination2' => 4,
                        'pagination3' => 5,
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(6,2,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 1,
                        'pagination0' => 2,
                        'pagination1' => 3,
                        'pagination2' => 4,
                        'pagination3' => 5,
                        'pagination4' => '',
                        'pagination10' => 6
                    ]
                ),
                array(7,2,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => '',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 1,
                        'pagination0' => 2,
                        'pagination1' => 3,
                        'pagination2' => 4,
                        'pagination3' => 5,
                        'pagination4' => '',
                        'pagination10' => 7
                    ]
                ),
                array(3,3,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => ' hidden',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => 1,
                        'pagination-1' => 2,
                        'pagination0' => 3,
                        'pagination1' => '',
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(4,3,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => 1,
                        'pagination-1' => 2,
                        'pagination0' => 3,
                        'pagination1' => 4,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(5,3,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => 1,
                        'pagination-1' => 2,
                        'pagination0' => 3,
                        'pagination1' => 4,
                        'pagination2' => 5,
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(6,3,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => 1,
                        'pagination-1' => 2,
                        'pagination0' => 3,
                        'pagination1' => 4,
                        'pagination2' => 5,
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 6
                    ]
                ),
                array(7,3,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => 1,
                        'pagination-1' => 2,
                        'pagination0' => 3,
                        'pagination1' => 4,
                        'pagination2' => 5,
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 7
                    ]
                ),
                array(4,4,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => ' hidden',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => 1,
                        'pagination-2' => 2,
                        'pagination-1' => 3,
                        'pagination0' => 4,
                        'pagination1' => '',
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(5,4,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => 1,
                        'pagination-2' => 2,
                        'pagination-1' => 3,
                        'pagination0' => 4,
                        'pagination1' => 5,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(6,4,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => 1,
                        'pagination-2' => 2,
                        'pagination-1' => 3,
                        'pagination0' => 4,
                        'pagination1' => 5,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 6
                    ]
                ),
                array(7,4,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => '',
                        'pagination-4' => '',
                        'pagination-3' => 1,
                        'pagination-2' => 2,
                        'pagination-1' => 3,
                        'pagination0' => 4,
                        'pagination1' => 5,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 7
                    ]
                ),
                array(5,5,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => ' hidden',
                        'paginationHide-4' => '',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => ' hidden',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => '',
                        'pagination-4' => 1,
                        'pagination-3' => 2,
                        'pagination-2' => 3,
                        'pagination-1' => 4,
                        'pagination0' => 5,
                        'pagination1' => '',
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(6,5,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 1,
                        'pagination-4' => '',
                        'pagination-3' => 2,
                        'pagination-2' => 3,
                        'pagination-1' => 4,
                        'pagination0' => 5,
                        'pagination1' => 6,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(7,5,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => '',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 1,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => 3,
                        'pagination-1' => 4,
                        'pagination0' => 5,
                        'pagination1' => 6,
                        'pagination2' => 7,
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(6,6,
                    [
                        'paginationHideLeftDots' => ' hidden',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => '',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => ' hidden',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 1,
                        'pagination-4' => 2,
                        'pagination-3' => 3,
                        'pagination-2' => 4,
                        'pagination-1' => 5,
                        'pagination0' => 6,
                        'pagination1' => '',
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(7,6,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 1,
                        'pagination-4' => '',
                        'pagination-3' => 3,
                        'pagination-2' => 4,
                        'pagination-1' => 5,
                        'pagination0' => 6,
                        'pagination1' => 7,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(7,7,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => ' hidden',
                        'paginationHide-10' => '',
                        'paginationHide-4' => '',
                        'paginationHide-3' => '',
                        'paginationHide-2' => '',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => ' hidden',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => ' hidden',
                        'pagination-10' => 1,
                        'pagination-4' => 3,
                        'pagination-3' => 4,
                        'pagination-2' => 5,
                        'pagination-1' => 6,
                        'pagination0' => 7,
                        'pagination1' => '',
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => ''
                    ]
                ),
                array(9,5,
                    [
                        'paginationHideLeftDots' => '',
                        'paginationHideRightDots' => '',
                        'paginationHide-10' => '',
                        'paginationHide-4' => ' hidden',
                        'paginationHide-3' => ' hidden',
                        'paginationHide-2' => ' hidden',
                        'paginationHide-1' => '',
                        'paginationHide0' => '',
                        'paginationHide1' => '',
                        'paginationHide2' => ' hidden',
                        'paginationHide3' => ' hidden',
                        'paginationHide4' => ' hidden',
                        'paginationHide10' => '',
                        'pagination-10' => 1,
                        'pagination-4' => '',
                        'pagination-3' => '',
                        'pagination-2' => '',
                        'pagination-1' => 4,
                        'pagination0' => 5,
                        'pagination1' => 6,
                        'pagination2' => '',
                        'pagination3' => '',
                        'pagination4' => '',
                        'pagination10' => 9
                    ]
                )
            );
        }

        /**
         * @dataProvider provider_setPageMenu
         */
        public function test_setPageMenu($nbrPages, $pagination, $expected) {
            # Given
            $obj = new PaginationNavigation();
            $template = [];
            $obj->init($template, $nbrPages);

            # When
            $obj->setPageMenu($pagination);

            # Then
            $this->assertEquals($obj->template, $expected);
        }

	}
}